<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.6">
  <POU Name="POU_blank_FB" Id="{06fdbe19-e246-445b-aa76-3d223c3c40af}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC POU_blank_FB
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU_blank_FB">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>